#IL 6th variables practice

name=input('what name : ')
num_small=input('number between 1-10 : ')
num_big=input('number between 100-1000 : ')
breakfast=input('what did you have for breakfast : ')
color=input('favorite color : ')
school=input('what school : ')
year=input('what year is it : ')
eye=input('whats your eye color : ')
age=input('your age : ')
subject=input('favorite subject : ')
print(name)
print(num_small)
print(num_big)
print(breakfast)
print(color)
print(school)
print(year)
print(eye)
print(age)
print(subject)