def what_num(num):
    if():
       num=1
       print("x|2|3")
       print("_____")
       print("4|5|6")
       print("_____")
       print("7|8|9")
    else():
        if():
            num=2
            print("1|x|3")
            print("_____")
            print("4|5|6")
            print("_____")
            print("7|8|9")
        else():
            if():
                num=3
                print("1|2|x")
                print("_____")
                print("4|5|6")
                print("_____")
                print("7|8|9")
            else():
                if():
                    num=4
                    print("1|2|3")
                    print("_____")
                    print("x|5|6")
                    print("_____")
                    print("7|8|9")
                else():
                    if():
                        num=5
                        print("1|2|3")
                        print("_____")
                        print("4|x|6")
                        print("_____")
                        print("7|8|9")
                    else():
                        if():
                            num=6
                            print("1|2|3")
                            print("_____")
                            print("4|5|x")
                            print("_____")
                            print("7|8|9")
                        else():
                            if():
                                num=7
                                print("1|2|3")
                                print("_____")
                                print("4|5|6")
                                print("_____")
                                print("x|8|9")
                            else():
                                if():
                                    num=8
                                    print("1|2|3")
                                    print("_____")
                                    print("4|5|6")
                                    print("_____")
                                    print("7|x|9")
                                else():
                                    if():
                                        num=9
                                        print("1|2|x")
                                        print("_____")
                                        print("4|5|6")
                                        print("_____")
                                        print("7|8|9")
